export const textMap: Record<string, string> = {
  Dashboard: '仪表盘',
  Users: '用户',
  User: '用户',
  Customers: '客户',
  Customer: '客户',
  Equipment: '设备',
  Audit: '审计',
  'Audit Logs': '审计日志',
  Backups: '备份管理',
  Groups: '角色组',
  Locations: '位置名称',
  Labels: '设备标签',
  'User Management': '用户管理',
  'Group Permissions': '角色组权限',
  'Customer Management': '客户管理',
  'Input voltage': '输入电压',
  Power: '功率',
  'Equipment Ledger': '设备台账',
  'Standard Library': '检测标准库',
  'Edit standard': '编辑标准',
  'Create standard': '新建标准',
  'Test Orders': '委托试验单',
  'Test order detail': '委托单详情',
  'Edit test order': '编辑委托单',
  'Create test order': '新建委托单',
  Samples: '样品信息',
  'Sample detail': '样品详情',
  'Sample flow records': '样品流转记录',
  'Receive samples': '接收样品',
  'Equipment Labels': '设备标签',
  'Sample Labels': '样品标签',
  'Equipment Usage Records': '设备使用记录',
  'Equipment Locations': '位置名称',
  'Backup Runs': '备份任务',
  'Group-based access control': '基于角色组的权限控制',
  'Sensitive field permissions': '敏感字段权限管理',
  'Locations, files, and labels': '位置、附件与标签管理',
  'Append-only operation records': '不可篡改的操作记录',
  'Accounts, departments, groups, lock state and first-login password controls.': '管理账号、部门、角色组、锁定状态和首次登录密码。',
  'Assign permissions directly to groups. A user may belong to multiple groups.': '为角色组分配权限；一个用户可以属于多个角色组。',
  'Manage selectable values such as sample status, conclusions and equipment states.': '管理样本状态、结论、设备状态等可选值。',
  'Customer registry, sensitive fields, contacts and filtered export.': '管理客户档案、敏感字段、联系人和筛选导出。',
  'Manage test standards, lifecycle status, catalogs and test items.': '管理检测标准、生命周期、目录和试验项目。',
  'Maintain the standard library without mixing the large form into the list.': '在独立页面维护标准库，避免大表单混入列表。',
  'Manage commission test orders, execution standards and expected sample rows.': '管理委托试验单、执行标准和样品信息。',
  'Use a dedicated page for the large commission order form.': '大字段量委托单使用独立页面维护。',
  'Review commission snapshots, execution standards and expected samples.': '查看委托快照、执行标准和样品信息。',
  'Track received physical samples, holder, location and flow records.': '跟踪已接收样品、持有人、位置和流转记录。',
  'Create physical sample records from one test order delivery.': '按委托单交付批次生成实体样品记录。',
  'Inspect physical sample state and append flow records.': '查看实体样品状态并追加流转记录。',
  'Review flow records across all received physical samples.': '查看全部实体样品的流转记录。',
  'Instrument ledger, calibration dates, locations and batch label printing.': '管理仪器台账、校准日期、位置和批量标签打印。',
  '40mm x 60mm equipment labels with QR code and XPD_LIMS footer.': '40mm x 60mm 设备标签，含二维码和 XPD_LIMS 页脚。',
  'Nested equipment locations with stable ordering and disable protection.': '管理多级位置名称、稳定排序和禁用保护。',
  'Append-only audit trail with before/after values, request IDs and export controls.': '只追加的审计记录，包含变更前后值、请求 ID 和导出控制。',
  'Manual backup run history, generated artifacts and permission-gated restore actions.': '手动备份历史、生成文件和受权限控制的恢复操作。',
  Filters: '筛选条件',
  Search: '搜索',
  Status: '状态',
  Department: '部门',
  Group: '角色组',
  Account: '账号',
  Security: '安全',
  Actions: '操作',
  Action: '动作',
  Name: '名称',
  Email: '邮箱',
  Phone: '电话',
  Address: '地址',
  Remark: '备注',
  Description: '描述',
  Code: '编码',
  Type: '类型',
  Level: '等级',
  Source: '来源',
  Industry: '行业',
  'Credit code': '统一社会信用代码',
  'Default contact': '默认联系人',
  Contacts: '联系人',
  'Contacts for': '联系人：',
  default: '默认',
  'No customer selected': '未选择客户',
  'Select a customer before managing contacts.': '请先选择客户再管理联系人。',
  'Loading customers': '正在加载客户',
  'No customers found': '未找到客户',
  'No available modules': '暂无可访问模块',
  'This account has no permissions yet. Contact an administrator to assign a role group.': '当前账号还没有任何权限，请联系管理员分配角色组。',
  'Adjust filters or create a new customer.': '调整筛选条件或新建客户。',
  'No standards found': '未找到标准',
  'Adjust filters or create a new standard.': '调整筛选条件或新建标准。',
  'New standard': '新建标准',
  'Loading test orders': '正在加载委托单',
  'Loading test order': '正在加载委托单',
  'Loading test order form': '正在加载委托单表单',
  'Test order': '委托单',
  'No test orders found': '未找到委托单',
  'Adjust filters or create a new commission order.': '调整筛选条件或新建委托单。',
  'New test order': '新建委托单',
  'Order profile': '委托单信息',
  'Customer snapshots': '客户快照',
  'Execution standards': '执行标准',
  'Sample rows': '样品信息',
  'Sample profile': '样品概况',
  'Received rows': '接收明细',
  Delivery: '交付批次',
  'New flow': '新增流转',
  'Flow records': '流转记录',
  'Sample flow card': '样品流转卡',
  'Flow history': '流转历史',
  'Print flow card': '打印流转卡',
  Operator: '操作人',
  'Calibration projects': '定标项目',
  'Maintain calibration project catalog and print project labels.': '维护定标项目并打印项目标签。',
  'Device calibration records': '设备定标记录',
  'Track device calibration events, standards and results.': '记录设备定标事件、标准件与结果。',
  'New calibration record': '新建定标记录',
  'Edit calibration record': '编辑定标记录',
  'Calibration record': '定标记录',
  'Record device calibration with standards, results and attachments.': '记录设备定标的标准件、结果与附件。',
  'Device calibration record detail.': '设备定标记录详情。',
  'Update device calibration record.': '更新设备定标记录。',
  qualified: '合格',
  unqualified: '不合格',
  'Scan sample flow': '扫码流转',
  'Scan or type a sample number, then record an allowed flow action.': '扫码或输入样品编号，记录允许的流转操作。',
  'sample no': '样品编号',
  'No actions available for current state': '当前状态没有可用操作',
  Confirm: '确认',
  Saved: '已保存',
  'Current holder': '当前持有人',
  'Current location': '当前位置',
  Holder: '持有人',
  'Holder to': '目标持有人',
  'Location to': '目标位置',
  'Storage condition': '储存条件',
  'Received date': '接收日期',
  'Batch no': '批次号',
  'Expected sample': '预期样品',
  'Appearance check': '外观检查',
  'Reject reason': '拒收原因',
  'Action type': '流转动作',
  'Add flow': '新增流转',
  'Add row': '新增明细',
  'Add standard': '新增标准',
  'Add sample': '新增样品',
  Remove: '移除',
  Receive: '接收',
  'Load expected rows': '载入预期样品',
  'Select order': '选择委托单',
  'Sample no': '样品编号',
  'No samples found': '未找到样品',
  'Receive samples from a test order before tracking flows.': '先从委托单接收样品，再跟踪流转记录。',
  'Delivery address and confirmations': '送检地址与确认',
  'Order no': '委托单号',
  'Contract no': '合同编号',
  'Order date': '委托日期',
  'Planned end date': '计划完成日期',
  'Urgency': '紧急程度',
  'Sample status': '样品状态',
  'Delivery method': '交付方式',
  'Outsourcing option': '准许检测分包',
  'Report forms': '报告形式（复选）',
  'Report requirements': '报告要求',
  'Report submission': '报告提交',
  Manual: '手动录入',
  Unset: '未设置',
  allowed: '允许',
  not_allowed: '不允许',
  electronic: '电子版',
  paper: '纸质版',
  formal_report: '正式报告',
  simple_report: '简版报告',
  electronic_report: '电子报告',
  english_report: '英文报告',
  self_pick: '自取',
  mail: '邮寄',
  Client: '委托方',
  'Client master': '委托方主数据',
  'Client address': '委托方地址',
  'Client contact': '委托方联系人',
  'Client phone': '委托方电话',
  'Manufacturer master': '制造商主数据',
  'Manufacturer company': '制造商',
  'Manufacturer address': '制造商地址',
  'Manufacturer contact': '制造商联系人',
  'Manufacturer phone': '制造商电话',
  Maker: '生产商',
  'Maker master': '生产商主数据',
  'Maker company': '生产商',
  'Maker address': '生产商地址',
  'Maker contact': '生产商联系人',
  'Maker phone': '生产商电话',
  'Client company': '委托单位',
  'Order from': '委托开始',
  'Order to': '委托结束',
  'Standard library': '标准库',
  'Standard number': '标准编号',
  'Chinese name': '中文名称',
  'Publish date': '发布日期',
  'Implement date': '实施日期',
  'Abolish date': '废止日期',
  'Replaced by': '替代标准',
  'Corresponding standard': '对应标准',
  Category: '分类',
  Language: '语言',
  'Standard code': '标准编号',
  'Standard name': '标准名称',
  'Item number': '项目编号',
  'Item name': '项目名称',
  'Report language': '报告语言',
  Qualifications: '资质',
  Requirement: '要求',
  Unit: '单位',
  Method: '方法',
  'Sample name': '样品名称',
  Specification: '规格',
  Quantity: '数量',
  'Detail content': '检测内容',
  'Lab name': '实验室',
  'Address contact': '收件人',
  'Address phone': '收件电话',
  'Address detail': '收件地址',
  'Client signature': '客户签名',
  'Client sign date': '客户签名日期',
  'Department confirm': '部门确认',
  'Department confirm date': '部门确认日期',
  'Lab confirm': '实验室确认',
  'Lab confirm date': '实验室确认日期',
  IP: 'IP',
  Hash: '哈希',
  Export: '导出',
  'Back to list': '返回列表',
  receive: '接收',
  lend: '领用',
  transfer: '转交',
  return_room: '归还样品室',
  send_out: '送外部',
  receive_back: '外部回收',
  return_client: '退还客户',
  scrap: '报废',
  position_change: '位置变更',
  'Loading contacts': '正在加载联系人',
  'No contacts': '暂无联系人',
  'Add a contact and mark one as the default contact.': '添加联系人，并设置一个默认联系人。',
  'Edit customer': '编辑客户',
  'Create customer': '新建客户',
  'New customer': '新建客户',
  'Equipment no': '设备编号',
  'Measurement range': '测量范围',
  Accuracy: '误差或精准度',
  Manufacturer: '制造商',
  Model: '型号',
  'Serial no': '序列号',
  Location: '位置',
  'No location': '无位置',
  'Purchase date': '购买日期',
  'Enable date': '启用日期',
  'Calibration date': '校准日期',
  'Next calibration': '下次校准',
  'Calibration duration': '校准周期',
  'Device image': '设备图片',
  Print: '打印',
  'Loading equipment': '正在加载设备',
  'No equipment found': '未找到设备',
  'Adjust filters or create the first equipment record.': '调整筛选条件或创建第一条设备记录。',
  'Edit equipment': '编辑设备',
  'Create equipment': '新建设备',
  'New equipment': '新建设备',
  'Due from': '到期开始',
  'Due to': '到期结束',
  'Preview source': '预览来源',
  'Equipment IDs': '设备 ID',
  Preview: '预览',
  'Loading labels': '正在加载标签',
  'No labels': '暂无标签',
  'Select equipment in the ledger or enter IDs to render labels.': '请在设备台账中选择设备，或输入 ID 生成标签。',
  'Temperature & Humidity Records': '温湿度记录',
  'Readings pushed automatically by monitoring devices, newest first. You can also record entries manually.':
    '监控设备自动上报的温湿度读数，最新在前；也可手动录入。',
  'equip no, site, room, person': '设备编号 / 场所 / 房间 / 记录人',
  'No readings found': '暂无温湿度记录',
  'Devices will appear here once they push readings.': '设备上报读数后将自动显示在这里。',
  'Loading readings': '正在加载温湿度记录',
  'Unable to load readings': '无法加载温湿度记录',
  'Add reading': '添加记录',
  'Edit reading': '编辑记录',
  'Save reading': '保存记录',
  'Unable to save reading': '无法保存记录',
  'Unable to delete reading': '无法删除记录',
  'Reading operation failed': '记录操作失败',
  'Equipment name': '设备名称',
  Temperature: '温度(℃)',
  Humidity: '湿度(%)',
  'Placement site': '放置场所',
  'Placement room': '放置房间',
  'Record person': '记录人',
  'Record time': '记录时间',
  'Location tree': '位置树',
  Parent: '父级',
  Root: '根节点',
  Sort: '排序',
  'Loading locations': '正在加载位置',
  'No locations': '暂无位置',
  'Create a root location, then add child rooms or benches.': '请先创建根位置，再添加房间或台位。',
  'Edit location': '编辑位置',
  'Create location': '新建位置',
  'New root': '新建根位置',
  'Audit filters': '审计筛选',
  Actor: '操作者',
  Module: '模块',
  'Request ID': '请求 ID',
  'Subject type': '对象类型',
  'Subject ID': '对象 ID',
  From: '开始',
  To: '结束',
  Time: '时间',
  Operation: '操作',
  Subject: '对象',
  Request: '请求',
  'Export JSON': '导出 JSON',
  'Loading audit logs': '正在加载审计日志',
  'No audit logs': '暂无审计日志',
  'No records match the current filters.': '没有符合当前筛选条件的记录。',
  'Record detail': '记录详情',
  'Select an audit record': '请选择审计记录',
  Before: '变更前',
  After: '变更后',
  Changed: '变更内容',
  'No record selected': '未选择记录',
  'Choose a row to inspect before and after values.': '请选择一行查看变更前后值。',
  Run: '任务',
  Artifacts: '文件',
  Size: '大小',
  Started: '开始时间',
  'Run backup': '执行备份',
  Restore: '恢复',
  'Loading backup runs': '正在加载备份任务',
  'No backup runs': '暂无备份任务',
  'Run the first manual backup to create a recorded checkpoint.': '执行第一次手动备份以创建检查点。',
  Items: '条目',
  Item: '条目',
  Value: '值',
  Label: '标签',
  Color: '颜色',
  Default: '默认',
  'Save location': '保存位置',
  Loading: '加载中',
  loading: '加载中',
  'Save Location': '保存位置',
  'Permission matrix': '权限矩阵',
  Permissions: '权限',
  Fields: '字段',
  'New group': '新建角色组',
  'Edit group': '编辑角色组',
  'Create group': '新建角色组',
  'Save group': '保存角色组',
  'Save matrix': '保存权限矩阵',
  'Loading groups': '正在加载角色组',
  'No groups': '暂无角色组',
  'Create a group before assigning permissions.': '请先创建角色组再分配权限。',
  'Select a group': '请选择角色组',
  'Edit group info': '编辑角色组信息',
  'New user': '新建用户',
  'Edit user': '编辑用户',
  'Create user': '新建用户',
  'Initial password': '初始密码',
  'Must change password': '用户下次登录后必须修改密码',
  'No department': '无部门',
  'Loading users': '正在加载用户',
  'No users found': '未找到用户',
  'Adjust filters or create the first operator account.': '调整筛选条件或创建第一个操作员账号。',
  'name or email': '姓名或邮箱',
  Lock: '锁定',
  Unlock: '解锁',
  Reset: '重置',
  'Reset password': '重置密码',
  Edit: '编辑',
  View: '查看',
  Save: '保存',
  Cancel: '取消',
  Delete: '删除',
  Disable: '禁用',
  All: '全部',
  active: '启用',
  disabled: '禁用',
  abolished: '已废止',
  replaced: '已替代',
  locked: '锁定',
  maintenance: '维护中',
  retired: '已退役',
  pending: '待处理',
  not_received: '未收样',
  partially_received: '部分收样',
  received: '已收样',
  testing: '检测中',
  rejected: '已拒收',
  cancelled: '已取消',
  retained: '留样',
  returned: '已退回',
  scrapped: '已报废',
  outsourced: '已分包',
  outsource_returned: '分包已回收',
  abnormal: '异常',
  normal: '普通',
  urgent: '加急',
  critical: '紧急',
  running: '运行中',
  failed: '失败',
  completed: '已完成',
  success: '成功',
  succeeded: '成功',
  System: '系统',
  'No update permission': '无更新权限',
  'Unable to load users': '无法加载用户',
  'Unable to load departments': '无法加载部门',
  'Unable to save user': '无法保存用户',
  'Unable to load groups': '无法加载角色组',
  'Unable to save group': '无法保存角色组',
  'Unable to load permissions': '无法加载权限',
  'Unable to save permissions': '无法保存权限',
  'Unable to load customers': '无法加载客户',
  'Unable to save customer': '无法保存客户',
  'Unable to load test orders': '无法加载委托单',
  'Unable to load test order': '无法加载委托单',
  'Unable to save test order': '无法保存委托单',
  'Unable to delete test order': '无法删除委托单',
  'Unable to load samples': '无法加载样品',
  'Unable to load sample': '无法加载样品',
  'Unable to receive samples': '无法接收样品',
  'Unable to load sample options': '无法加载样品选项',
  'Unable to load sample flows': '无法加载样品流转',
  'Unable to save sample flow': '无法保存样品流转',
  'Invalid receive payload': '接样内容无效，请检查后重试',
  'Invalid flow payload': '流转内容无效，请检查后重试',
  'Unable to load equipment': '无法加载设备',
  'Unable to save equipment': '无法保存设备',
  'Unable to load locations': '无法加载位置',
  'Unable to save location': '无法保存位置',
  'Add contact': '新增联系人',
  'Edit contact': '编辑联系人',
  'Create contact': '新建联系人',
  'Save contact': '保存联系人',
  'Unable to load contacts': '无法加载联系人',
  'Contact operation failed': '联系人操作失败',
  'phone hidden': '手机号已隐藏',
  'email hidden': '邮箱已隐藏',
  'Unclassified': '未分类',
  'name, credit, phone': '名称、信用代码、电话',
  'name, no., model': '名称、编号、型号',
  'No.': '编号',
  'Manual files': '说明书文件',
  'Instruction files': '操作规程文件',
  'Calibration files': '校准文件',
  'Other files': '其他文件',
  'comma separated file refs': '多个文件引用请用英文逗号分隔',
  'Unable to create label preview': '无法生成标签预览',
  'Location cannot be disabled': '该位置无法禁用',
  'Unable to disable equipment': '无法禁用设备',
  'Unable to delete customer': '无法删除客户',
  'Unable to load audit logs': '无法加载审计日志',
  'Unable to start backup': '无法启动备份',
  'Unable to restore backup': '无法恢复备份',
  'Unable to load backups': '无法加载备份',
  'Unable to load permission catalog': '无法加载权限目录',
  'User operation failed': '用户操作失败',
  'Manual administrator lock': '管理员手动锁定',
  'first login password change': '首次登录需改密',
  'password ready': '密码可用',
  'System group': '系统角色组',
  super_admin: '超级管理员',
  system_admin: '系统管理员',
  customer_viewer: '客户查看员',
  customer_editor: '客户编辑员',
  equipment_manager: '设备管理员',
  test_order_manager: '委托单管理员',
  sample_manager: '样品管理员',
  auditor: '审计员',
  'System Admin': '系统管理员',
  'Customer Viewer': '客户查看员',
  'Customer Editor': '客户编辑员',
  'Equipment Manager': '设备管理员',
  'Test Order Manager': '委托单管理员',
  'Sample Manager': '样品管理员',
  Auditor: '审计员',
  'Locked User': '锁定用户',
  hidden: '已隐藏',
  'Editing': '正在编辑',
  'Backup': '备份',
  'Backup #': '备份 #',
  Created: '创建时间',
  Path: '路径',
  Error: '错误',
  'Request failed': '请求失败',
  'Loading data': '正在加载数据',
  'Name is required': '请填写名称',
  'Equipment number is required': '请填写设备编号',
  'Valid email is required': '请输入有效邮箱',
  'Password must be at least 8 characters': '密码至少 8 位',
  'The email field is required.': '请填写邮箱。',
  'The password field is required.': '请填写密码。',
  'The selected email is invalid.': '邮箱或密码不正确。',
  auth_failed: '邮箱或密码不正确',
  field_update_forbidden: '没有权限修改该字段',
  default_contact_delete_rejected: '默认联系人不能删除，请先设置其他默认联系人',
  password_change_required: '请先修改密码后再继续操作',
  'Password must be changed before accessing this API.': '请先修改密码后再访问系统。',
  'The given data was invalid.': '提交的数据无效，请检查后重试。',
  Unauthorized: '未登录或登录已过期',
  Forbidden: '没有权限执行该操作',
  'Not Found': '资源不存在',
  'Server Error': '服务器错误',
}

export function zhText(value?: string | null) {
  if (!value) return value
  return textMap[value] ?? value
}

export function zhErrorText(value?: string | null) {
  if (!value) return value
  if (textMap[value]) return textMap[value]
  return value
    .replace(/^The (.+) field is required\.$/, '请填写$1。')
    .replace(/^The (.+) must be a valid email address\.$/, '$1格式不正确。')
    .replace(/^The (.+) must be at least (\d+) characters\.$/, '$1至少需要$2个字符。')
    .replace(/^The (.+) must not be greater than (\d+) characters\.$/, '$1不能超过$2个字符。')
    .replace(/^The selected (.+) is invalid\.$/, '选择的$1无效。')
    .replace(/^The (.+) must be an integer\.$/, '$1必须是整数。')
    .replace(/^The (.+) field must be true or false\.$/, '$1必须为是或否。')
    .replace(/^The (.+) must be an array\.$/, '$1必须是数组。')
    .replace(/^The (.+) has already been taken\.$/, '$1已存在。')
}
